### ISSUE TITLE
How to use local video

### ISSUE THREAD

**Issue by binoculars88** [TivonChen/novonity-plugin-vr#2]
How can I play a local video?
I've tried:
`vr.startPlaying('www/test.mp4');` and `vr.startPlaying('test.mp4');`

And also (using cordova-file-plugin):
`var path = cordova.file.applicationDirectory + 'www/test.mp4';`
`vr.startPlaying(path);`

Both don't work. I've put test.mp4 in the www folder in Ionic.

Any help is much appreciated!

**Comment by binoculars88** [comment]
If worked around it by changing
`initFileURLWithPath` to `initWithString` in VrModule.m

**Comment by tivonchen** [comment]
u have to try the full path of the video file, such as file://xxx.
